/* Demo fixtures and normalized provider fallbacks live in data.js / services.js. */
const data=window.AeroSenseData.cities;
const names=["PM2.5","PM10","NO2","SO2","O3"], units=["µg/m³","µg/m³","ppb","ppb","ppb"], colors=["#43a399","#e0b84c","#e58c4b","#9b7ab4","#5f9dc0"];
let city="Chennai",range="24h",profile="general",compare=["Chennai","Bengaluru","Hyderabad"],activePayload=null,activeData=data[city],dataMode="auto",requestSerial=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function risk(n){return n<=50?"Good":n<=100?"Moderate":n<=150?"Sensitive groups":n<=200?"Unhealthy":n<=300?"Very unhealthy":"Hazardous"}
function color(n){return n<=50?"#4e9c73":n<=100?"#a1812d":n<=150?"#aa753c":n<=200?"#b56e36":n<=300?"#ac5c52":"#905889"}
function spark(a,c){let mn=Math.min(...a),mx=Math.max(...a),p=a.map((v,i)=>(i*56/(a.length-1))+","+ (20-(v-mn)/(mx-mn||1)*16)).join(" ");return '<svg class="spark" viewBox="0 0 56 22"><polyline fill="none" stroke="'+c+'" stroke-width="1.5" points="'+p+'"/></svg>'}
function render(){
 const d={...data[city],...activeData},status=activePayload?.status||"demo",sv=d.aqi===null?"#829297":color(d.aqi),weather=d.weather||AeroSenseServices.demoWeather(city),now=Date.now();
 const keys=["pm25","pm10","no2","so2","o3"],values=[d.pm,d.pm10,d.no2,d.so2,d.o3];
 const livePoints=status==="demo"?[]:(activePayload?.hourly||[]).filter(p=>p.time&&Date.parse(p.time+"+05:30")<=now&&Date.parse(p.time+"+05:30")>=now-86400000);
 $("#weatherMini").textContent=(weather.source==="DEMO DATA"&&status!=="demo"?"Demo weather · ":"")+(weather.tempC===null?"—":weather.tempC+"°")+" · "+(weather.summary||"Weather unavailable");
 $("#aqiNumber").textContent=d.aqi??"—";$("#aqiNumber").style.color=sv;$("#riskTag").textContent=d.aqi===null?"UNAVAILABLE":risk(d.aqi).toUpperCase();$("#riskTag").style.color=sv;
 $("#aqiCopy").textContent=d.aqi===null?"No usable AQI was returned for this location.":d.aqi>150?"Air quality is elevated. Sensitive groups may notice effects.":d.aqi>100?"Some people may be affected, especially during prolonged outdoor activity.":"Air conditions are relatively favorable for most everyday activities.";
 $("#changeValue").textContent=(d.delta>0?"↗ ":"↘ ")+Math.abs(d.delta||0)+"%";$("#changeValue").style.color=d.delta>0?"#d68043":"#4c9d7d";$("#primaryPollutant").innerHTML="PM2.5 <span>· "+(d.pm===null?"Unavailable":d.pm+" µg/m³")+"</span>";$("#outlookText").textContent="Demo outlook · not live prediction";
 $("#airDataSource").textContent=activePayload?.air?.source||"DEMO DATA";$("#airDataNote").textContent=status==="demo"?"ⓘ Deterministic demo fixtures · no live feed available.":"ⓘ CAMS model forecast, not a ground-monitor reading.";
 $("#aqiMeter span").style.left=d.aqi===null?"0%":Math.min(94,d.aqi/5)+"%";$("#aqiMeter span").style.background=sv;$("#mapCity").textContent=city;$("#mapRisk").textContent=(d.aqi===null?"AQI unavailable":risk(d.aqi))+" · PM2.5";$("#mapDataStatus").textContent=status==="demo"?"DEMO DATA":"Selected: "+status+" · others: demo";
 $("#pollutantDataStatus").textContent=status==="demo"?"●  DEMO DATA":status==="stale"?"●  STALE MODEL":"●  OPEN-METEO MODEL";$("#footerDataMode").textContent=status==="demo"?"DEMO BUILD · SIMULATED ENVIRONMENTAL DATA":status==="stale"?"STALE MODEL DATA · DEMO PREDICTIONS / HISTORY":"OPEN-METEO MODEL DATA · DEMO PREDICTIONS / HISTORY";
 $("#markerAqi").textContent=d.aqi??"—";$("#mainMarker").style.background=sv;$("#mapGlow").style.left={Chennai:"42%",Bengaluru:"20%",Hyderabad:"68%",Delhi:"60%",Mumbai:"78%"}[city];$("#pmRise").textContent=(d.rise??0)+"%";
 const statusEl=$("#dataStatus");statusEl.className="demo-chip status-"+status;statusEl.innerHTML="<span></span>"+(status==="live"?"LIVE MODEL DATA":status==="partial"?"PARTIAL MODEL DATA":status==="stale"?"STALE MODEL DATA":"DEMO DATA");$("#modeToggle").textContent=dataMode==="demo"?"Try live data":"Use demo data";const stamp=activePayload?.timestamp;$("#updatedLabel").textContent=stamp?(status==="stale"?"Last model time · ":"Model time · ")+stamp:(status==="demo"?"Fixed demo fixtures":"Waiting for feed");
 const cardUnits=names.map((_,i)=>status==="demo"?units[i]:"µg/m³");
 $("#pollutants").innerHTML=values.map((v,i)=>{const series=status==="demo"?d.series.slice(-8).map(x=>x*(.45+i*.1)):livePoints.map(p=>p[keys[i]]).filter(Number.isFinite).slice(-8);const pair=series.slice(-2);const ch=status==="demo"?Math.round((d.delta||0)*[.8,.55,.4,.22,.3][i]):pair.length===2&&pair[0]!==0?Math.round((pair[1]-pair[0])/pair[0]*100):null;const state=v===null?"Unavailable":v>100?"High":v>45?"Elevated":v>25?"Moderate":"Low";const trend=ch===null?'<span>—</span><span>Change unavailable</span>':'<span class="'+(ch>0?"trend-up":"")+'">'+(ch>0?"↗ ":"↘ ")+Math.abs(ch)+'%</span><span>'+(status==="demo"?"vs demo period":"vs prior model hour")+'</span>';const sparkline=series.length>1?spark(series,colors[i]):'<small class="trend-unavailable">Trend unavailable</small>';return '<article class="card pollutant-card"><div class="poll-top"><span class="poll-name">'+names[i]+(status!=="demo"&&i>1?" · µg/m³":"")+'</span><span class="poll-status">'+state+'</span></div><div class="poll-value">'+(v===null?"—":v)+' <small>'+cardUnits[i]+'</small></div><div class="poll-change">'+trend+'</div>'+sparkline+'</article>'}).join("");
 const factors=[["Traffic activity","Not measured",null],["Wind speed",weather.windKmh===null?"Unavailable":d.wind.toUpperCase(),weather.windKmh===null?null:Math.min(100,Math.round(weather.windKmh*3))],["Humidity",weather.humidityPct===null?"Unavailable":d.humidity.toUpperCase(),weather.humidityPct],["Temperature",weather.tempC===null?"Unavailable":d.temperature.toUpperCase(),weather.tempC===null?null:Math.min(100,Math.round(weather.tempC*2))],["Rainfall",weather.precipMm===null?"Unavailable":d.rain.toUpperCase(),weather.precipMm===null?null:Math.min(100,weather.precipMm*20)]];
 $("#factors").innerHTML=factors.map(f=>'<div class="factor"><span class="factor-name">'+f[0]+'</span><span class="factor-bar"><i style="width:'+(f[2]===null?0:f[2])+'%"></i></span><span class="factor-level">'+f[1]+'</span></div>').join("");
 timeline(d);forecast(d);advisor(d);comparison();history();recommendations(d)
}
function lineChart(vals,labels,markAnomaly=false){if(vals.length<2)return '<div class="empty-chart">Not enough observations for this chart.</div>';let mn=Math.min(...vals),mx=Math.max(...vals),max=Math.ceil(mx*1.18/10)*10||10,W=640,H=130,p=26,x=i=>p+i*(W-p-8)/(vals.length-1),y=v=>12+(max-v)*(H-32)/max,pts=vals.map((v,i)=>x(i)+","+y(v)).join(" "),ai=Math.floor(vals.length*.77);return '<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none"><defs><linearGradient id="areaFade" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#55b1a5" stop-opacity=".19"/><stop offset="1" stop-color="#55b1a5" stop-opacity="0"/></linearGradient></defs>'+[.2,.5,.8].map(t=>'<line class="chart-grid" x1="'+p+'" x2="'+(W-8)+'" y1="'+(12+(H-32)*t)+'" y2="'+(12+(H-32)*t)+'"/>').join("")+'<polygon class="chart-area" points="'+p+','+(H-20)+' '+pts+' '+(W-8)+','+(H-20)+'"/><polyline class="chart-line" points="'+pts+'"/>'+(markAnomaly?'<line class="anomaly-line" x1="'+x(ai)+'" x2="'+x(ai)+'" y1="'+(y(vals[ai])-17)+'" y2="'+(H-20)+'"/><circle class="anomaly-point" cx="'+x(ai)+'" cy="'+y(vals[ai])+'" r="4"/>':"")+[0,Math.floor((vals.length-1)/3),Math.floor(2*(vals.length-1)/3),vals.length-1].map((i,j)=>'<text class="chart-tick" x="'+x(i)+'" y="'+(H-2)+'" text-anchor="'+(j===0?"start":j===3?"end":"middle")+'">'+labels[j]+'</text>').join("")+'</svg>'}
function timeline(d){let source="DEMO DATA · deterministic fixture",a=d.series.slice(),idx=names.indexOf($("#pollutantSelect").value),pollutant=$("#pollutantSelect").value,keys={"PM2.5":"pm25",PM10:"pm10",NO2:"no2",SO2:"so2",O3:"o3"},live=activePayload&&activePayload.status!=="demo"&&range==="24h";if(live){a=activePayload.hourly.filter(p=>p.time&&Date.parse(p.time+"+05:30")<=Date.now()&&Date.parse(p.time+"+05:30")>=Date.now()-86400000&&p[keys[pollutant]]!==null).map(p=>p[keys[pollutant]]);source="Open-Meteo model · previous 24h · µg/m³"}else{if(range==="7d")a=a.filter((_,i)=>i%3===0);if(range==="30d")a=a.filter((_,i)=>i%5===0);a=a.map(v=>Math.round(v*[1,.84,.5,.23,.4][idx]+idx*4));if(activePayload&&activePayload.status!=="demo")source="DEMO DATA · longer history unavailable"}let labels=range==="24h"?["−24h","−18h","−12h","Now"]:range==="7d"?["Mon","Wed","Fri","Sun"]:["Sep 6","Sep 16","Sep 26","Oct 5"];$("#timelineSource").textContent=source;$("#timelineChart").innerHTML=lineChart(a,labels,!live);$("#anomalyCallout").style.display=live?"none":"flex";$("#anomalyKey").style.display=live?"none":"";$("#anomalyDescription").textContent=live?"":(activePayload&&activePayload.status!=="demo"?"Synthetic sample marker; no historical feed is available for this range.":pollutant+" sample spike, included as deterministic demo data.");if(live)$("#anomalyHeadline").textContent="No live anomaly alert"}
function forecast(d){if(d.aqi===null){$("#forecastChart").textContent="Current AQI unavailable; prediction display withheld.";$("#forecastHours").innerHTML="";return}let vals=AeroSenseServices.demoPrediction(city),all=[Math.round(d.aqi*.83),Math.round(d.aqi*.93),d.aqi,...vals],W=700,H=132,p=24,max=Math.ceil(Math.max(...all)*1.22/20)*20,x=i=>p+i*(W-p-15)/(all.length-1),y=v=>16+(max-v)*(H-29)/max,pts=all.map((v,i)=>x(i)+","+y(v)).join(" ");$("#forecastChart").innerHTML='<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none"><line x1="'+p+'" x2="'+(W-15)+'" y1="'+y(d.aqi)+'" y2="'+y(d.aqi)+'" stroke="#b9c7c7" stroke-dasharray="4 4"/><polygon points="'+all.slice(2).map((v,i)=>x(i+2)+","+y(v*1.13)).join(" ")+" "+all.slice(2).reverse().map((v,i)=>x(all.length-1-i)+","+y(v*.86)).join(" ")+'" fill="#dcefeb" opacity=".75"/><polyline points="'+pts+'" fill="none" stroke="#3c9e92" stroke-width="2.5" stroke-dasharray="5 4"/>'+all.map((v,i)=>'<text x="'+x(i)+'" y="'+(H-1)+'" text-anchor="middle" fill="#a0adae" font-size="8" font-family="DM Sans">'+(i<2?"−"+(2-i)+"h":"+"+(i-2)+"h")+'</text>').join("")+'</svg>';$("#forecastHours").innerHTML=vals.map((v,i)=>'<div class="forecast-hour"><span>+'+(i+1)+'h</span><b>'+v+' AQI</b><em>'+risk(v)+'</em></div>').join("")}
function advisor(d){if(d.aqi===null){$("#bestWindow").textContent="Unavailable";$("#windowAqi").textContent="Current AQI unavailable; demo estimate withheld.";$("#profileAdvice").textContent="Check a current air-quality source before planning outdoor activity.";return}let w=d.aqi>180?"Before 7:00 AM":d.aqi>120?"Before 8:00 AM":"Late morning · 10:00 AM";$("#bestWindow").textContent=w;$("#windowAqi").textContent="Demo AQI estimate: "+d.window+" · "+risk(d.window);$("#profileAdvice").textContent={general:"Choose a shorter, less strenuous outing during this window.",athlete:"Avoid intense outdoor exercise during the predicted pollution peak; consider an indoor session.",child:"Consider outdoor play during the cleaner window and keep activity flexible.",elderly:"Plan a shorter outdoor visit during the lower-pollution window.",sensitive:"Prefer the cleaner window and reduce prolonged exposure if conditions worsen."}[profile]}
function comparison(){$("#compareSelects").innerHTML=compare.map((c,i)=>'<select data-compare="'+i+'" aria-label="Comparison city '+(i+1)+'">'+Object.keys(data).map(n=>'<option '+(n===c?"selected":"")+'>'+n+'</option>').join("")+'</select>').join("");$("#compareChart").innerHTML=compare.map(c=>'<div class="compare-row"><span class="compare-city">'+c+'</span><span class="compare-bar"><i style="width:'+Math.min(100,data[c].aqi/3)+'%"></i></span><span class="compare-val">'+data[c].aqi+'</span></div>').join("");let s=compare.slice().sort((a,b)=>data[a].aqi-data[b].aqi);$("#comparisonSummary").innerHTML='<span class="summary-chip">Cleanest <b>'+s[0]+'</b></span><span class="summary-chip">Highest AQI <b>'+s[s.length-1]+'</b></span><span class="summary-chip">Predicted peak <b>'+compare.slice().sort((a,b)=>Math.max(...data[b].future)-Math.max(...data[a].future))[0]+'</b></span>'}
function history(){$("#historyList").innerHTML=AeroSenseServices.demoHistory(city).map(e=>'<div class="history-event"><span class="history-date">'+e.date+' · '+city.slice(0,3).toUpperCase()+'</span><div><b>'+e.title+'</b><p>'+e.description+'</p><a href="#history">Demo record · no source implied ↗</a></div></div>').join("")}
function recommendations(d){let keys=AeroSenseServices.demoRecommendationKeys(d.aqi),copy={"Limit prolonged outdoor exposure":"Move nonessential outdoor plans to a cleaner time window.","Choose lower-emission travel":"When practical, combine trips or use shared transport.","Check conditions before heading out":"Revisit local air readings later; conditions can change.","Choose a lower-pollution time":"The early morning window is forecast to be cleaner.","Keep outdoor plans flexible":"Consider shortening strenuous activity if air worsens.","Reduce avoidable emissions":"Combine nearby errands or choose shared transport.","Plan around the cleaner window":"Predictions suggest a better time later today.","Prefer lighter activity if needed":"Take breaks if outdoor conditions feel uncomfortable.","Check again before longer outings":"Forecasts are estimates and can shift.","Enjoy outdoor plans thoughtfully":"Current demo conditions are comparatively favorable.","Keep an eye on changing conditions":"Air quality can vary through the day.","Choose shared travel where practical":"Small choices can reduce local emissions."};$("#recIntro").textContent=d.aqi===null?"Current AQI unavailable. Showing general demo guidance.":"Guidance adapted to "+risk(d.aqi).toLowerCase()+" conditions."+(profile!=="general"?" Personalized for your selected profile.":"");$("#recommendationsList").innerHTML=keys.map(k=>'<div class="recommendation"><span class="rec-check">✓</span><div><b>'+k+'</b><p>'+copy[k]+'</p></div></div>').join("")}
function toast(m){let t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function modal(title,body){$("#modalTitle").textContent=title;$("#modalBody").textContent=body;$("#modalBackdrop").classList.add("show")}
async function loadCity(){const ticket=++requestSerial;if(activePayload?.city!==city){activePayload=null;activeData=data[city];render()}$("#dataStatus").className="demo-chip status-loading";$("#dataStatus").innerHTML="<span></span> LOADING DATA";$("#updatedLabel").textContent="Checking Open-Meteo…";$("#refreshData").disabled=true;try{let payload=await AeroSenseServices.load(city,{mode:dataMode});if(ticket!==requestSerial)return;activePayload=payload;activeData=payload.status==="demo"?data[city]:AeroSenseServices.getLiveOptions(payload);render();if(payload.status==="demo"&&payload.error)$("#updatedLabel").textContent="Demo fallback · live feed unavailable"}finally{if(ticket===requestSerial)$("#refreshData").disabled=false}}
$("#citySelect").innerHTML=Object.keys(data).map(c=>"<option>"+c+"</option>").join("");$("#citySelect").addEventListener("change",e=>{city=e.target.value;loadCity()});
$$(".map-marker[data-city]").forEach(b=>b.addEventListener("click",()=>{$("#citySelect").value=b.dataset.city;city=b.dataset.city;loadCity()}));
$("#pollutantSelect").addEventListener("change",()=>timeline({...data[city],...activeData}));$("#rangeTabs").addEventListener("click",e=>{if(e.target.dataset.range){range=e.target.dataset.range;$$('#rangeTabs button').forEach(b=>b.classList.toggle("active",b===e.target));timeline({...data[city],...activeData})}});
$("#profileSelect").addEventListener("change",e=>{profile=e.target.value;advisor({...data[city],...activeData});recommendations({...data[city],...activeData})});
$("#compareSelects").addEventListener("change",e=>{if(e.target.dataset.compare!==undefined){compare[+e.target.dataset.compare]=e.target.value;comparison()}});
$("#refreshData").addEventListener("click",()=>{dataMode="auto";loadCity()});$("#modeToggle").addEventListener("click",()=>{dataMode=dataMode==="demo"?"auto":"demo";loadCity()});
$("#addCompare").addEventListener("click",()=>{if(compare.length>=3){toast("Compare up to three locations at a time.");return}compare.push(Object.keys(data).find(c=>!compare.includes(c)));comparison()});
$("#themeToggle").addEventListener("click",()=>document.body.classList.toggle("dark"));$("#menuToggle").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
let mapZoom=1;function setMapZoom(v){mapZoom=Math.max(1,Math.min(1.28,v));let el=$("#mapVisual");el.style.setProperty("--map-zoom",mapZoom);el.classList.toggle("zoomed",mapZoom>1.02)}
$("#mapReset").addEventListener("click",()=>{setMapZoom(1);toast("Map centered on "+city)});$("#zoomIn").addEventListener("click",()=>setMapZoom(mapZoom+.08));$("#zoomOut").addEventListener("click",()=>setMapZoom(mapZoom-.08));
$$(".more-button").forEach(b=>b.addEventListener("click",()=>modal("Chart data sources",activePayload?.status==="demo"?"Chart values are deterministic demo fixtures. Change the range or pollutant to explore the sample series.":range==="24h"?"The 24-hour pollutant chart uses Open-Meteo model output. Forecast and best-time estimates remain deterministic demo logic.":"This extended chart range uses deterministic demo fixtures; Open-Meteo history is not available in this view.")));
$("#mapLocations").addEventListener("click",()=>modal("Explore city readings","Choose a city from the selector or click a marker. Marker positions are schematic. The selected city follows the data source shown in the header; unselected marker values remain demo fixtures."));
$("#historyInfo").addEventListener("click",()=>modal("Demo environmental history","These sample entries illustrate a future product format only. They are not reports of actual incidents, inspections, violations, or regulatory actions. No source is implied."));
$("#profileOpen").addEventListener("click",()=>modal("Guest workspace",activePayload?.status==="demo"?"AeroSense is showing deterministic demo data. No account is required; your profile choice stays in this browser session.":"AeroSense is showing Open-Meteo model data with demo predictions and history. No account is required; your profile choice stays in this browser session."));
$("#profileTop").addEventListener("click",()=>modal("Guest workspace",activePayload?.status==="demo"?"AeroSense is showing deterministic demo data. No account is required; your profile choice stays in this browser session.":"AeroSense is showing Open-Meteo model data with demo predictions and history. No account is required; your profile choice stays in this browser session."));
$("#modalClose").addEventListener("click",()=>$("#modalBackdrop").classList.remove("show"));$("#modalOkay").addEventListener("click",()=>$("#modalBackdrop").classList.remove("show"));$("#modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")e.target.classList.remove("show")});document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#modalBackdrop").classList.remove("show")});
let titles={overview:"Overview",trends:"Pollution trends",prediction:"Prediction",history:"Environmental history",recommendations:"Recommendations"};
function go(v){let ids={overview:"overviewView",trends:"timelineSection",prediction:"predictionSection",history:"historySection",recommendations:"recommendationsSection"};document.getElementById(ids[v]||ids.overview).scrollIntoView({behavior:"smooth",block:"start"});$("#crumb").textContent=titles[v];$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===v));$("#sidebar").classList.remove("open")}
$$("[data-view]").forEach(e=>e.addEventListener("click",ev=>{ev.preventDefault();go(e.dataset.view)}));
let obs=new IntersectionObserver(es=>{let v=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;let map={overviewView:"overview",timelineSection:"trends",predictionSection:"prediction",historySection:"history",recommendationsSection:"recommendations"},k=map[v.target.id];if(k){$("#crumb").textContent=titles[k];$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===k))}},{rootMargin:"-20% 0px -68% 0px",threshold:[0,.1,.4]});
["overviewView","timelineSection","predictionSection","historySection","recommendationsSection"].forEach(id=>obs.observe(document.getElementById(id)));
function enterDashboard(){$("#landing").hidden=true;$("#landing").style.display="none";$("#appShell").classList.remove("app-hidden");window.scrollTo({top:0,behavior:"instant"});loadCity()}
function returnHome(e){e.preventDefault();$("#appShell").classList.add("app-hidden");$("#landing").hidden=false;$("#landing").style.display="block";window.scrollTo({top:0,behavior:"smooth"})}
$$("[data-enter]").forEach(b=>b.addEventListener("click",enterDashboard));$("#dashboardBrand").addEventListener("click",returnHome);$("#landingBrand").addEventListener("click",e=>{e.preventDefault();window.scrollTo({top:0,behavior:"smooth"})});
if(location.hash==="#overview"||location.hash==="#dashboard")enterDashboard();else render();
