/* Demo fixtures and normalized provider fallbacks live in data.js / services.js. */
const data=window.AeroSenseData.cities;
const names=["PM2.5","PM10","NO2","SO2","O3"], units=["µg/m³","µg/m³","ppb","ppb","ppb"], colors=["#43a399","#e0b84c","#e58c4b","#9b7ab4","#5f9dc0"];
let city="Chennai",range="24h",profile="general",compare=["Chennai","Bengaluru","Hyderabad"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function risk(n){return n<=50?"Good":n<=100?"Moderate":n<=150?"Sensitive groups":n<=200?"Unhealthy":n<=300?"Very unhealthy":"Hazardous"}
function color(n){return n<=50?"#4e9c73":n<=100?"#a1812d":n<=150?"#aa753c":n<=200?"#b56e36":n<=300?"#ac5c52":"#905889"}
function spark(a,c){let mn=Math.min(...a),mx=Math.max(...a),p=a.map((v,i)=>(i*56/(a.length-1))+","+ (20-(v-mn)/(mx-mn||1)*16)).join(" ");return '<svg class="spark" viewBox="0 0 56 22"><polyline fill="none" stroke="'+c+'" stroke-width="1.5" points="'+p+'"/></svg>'}
function render(){let d=AeroSenseServices.demoCurrent(city),sv=color(d.aqi),weather=AeroSenseServices.demoWeather(city);$("#weatherMini").textContent="☀  "+weather.tempC+"°  ·  "+weather.summary;$("#aqiNumber").textContent=d.aqi;$("#aqiNumber").style.color=sv;$("#riskTag").textContent=risk(d.aqi).toUpperCase();$("#riskTag").style.color=sv;$("#aqiCopy").textContent=d.aqi>150?"Air quality is elevated. Sensitive groups may notice effects.":d.aqi>100?"Some people may be affected, especially during prolonged outdoor activity.":"Air conditions are relatively favorable for most everyday activities.";$("#changeValue").textContent=(d.delta>0?"↗ ":"↘ ")+Math.abs(d.delta)+"%";$("#changeValue").style.color=d.delta>0?"#d68043":"#4c9d7d";$("#primaryPollutant").innerHTML="PM2.5 <span>· "+d.pm+" µg/m³</span>";$("#outlookText").innerHTML=(d.aqi>140?"Elevated":"Near current levels")+" for ~"+(d.aqi>140?5:3)+" hours <span class=\"outlook-arrow\">↗</span>";$("#aqiMeter span").style.left=Math.min(94,d.aqi/5)+"%";$("#aqiMeter span").style.background=sv;$("#mapCity").textContent=city;$("#mapRisk").textContent=risk(d.aqi)+" · PM2.5";$("#markerAqi").textContent=d.aqi;$("#mainMarker").style.background=sv;$("#mapGlow").style.left={Chennai:"42%",Bengaluru:"20%",Hyderabad:"68%",Delhi:"60%",Mumbai:"78%"}[city];$("#pmRise").textContent=d.rise+"%";
 $("#pollutants").innerHTML=[d.pm,d.pm10,d.no2,d.so2,d.o3].map((v,i)=>{let ch=Math.round(d.delta*[.8,.55,.4,.22,.3][i]),st=v>100?"High":v>45?"Elevated":v>25?"Moderate":"Low";return '<article class="card pollutant-card"><div class="poll-top"><span class="poll-name">'+names[i]+'</span><span class="poll-status">'+st+'</span></div><div class="poll-value">'+v+' <small>'+units[i]+'</small></div><div class="poll-change"><span class="'+(ch>0?"trend-up":"")+'">'+(ch>0?"↗ ":"↘ ")+Math.abs(ch)+'%</span><span>vs prev. period</span></div>'+spark(d.series.slice(-8).map(x=>x*(.45+i*.1)),colors[i])+'</article>'}).join("");
 let factors=[["Traffic activity",d.aqi>150?"HIGH":"MODERATE",d.aqi>150?84:59],["Wind speed",d.wind.toUpperCase(),d.wind.toLowerCase().includes("low")?82:46],["Humidity",d.humidity.toUpperCase(),d.humidity==="High"?68:45],["Temperature",d.temperature.toUpperCase(),d.temperature==="High"?64:46],["Rainfall",d.rain.toUpperCase(),d.rain==="None"?15:d.rain==="Low"?25:56]];
 $("#factors").innerHTML=factors.map(f=>'<div class="factor"><span class="factor-name">'+f[0]+'</span><span class="factor-bar"><i style="width:'+f[2]+'%"></i></span><span class="factor-level">'+f[1]+'</span></div>').join("");
 timeline(d);forecast(d);advisor(d);comparison();history();recommendations(d)}
function lineChart(vals,labels){let W=640,H=130,p=26,max=Math.ceil(Math.max(...vals)*1.22/20)*20,x=i=>p+i*(W-p-8)/(vals.length-1),y=v=>12+(max-v)*(H-32)/max,pts=vals.map((v,i)=>x(i)+","+y(v)).join(" "),ai=Math.floor(vals.length*.77);return '<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none"><defs><linearGradient id="areaFade" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#55b1a5" stop-opacity=".19"/><stop offset="1" stop-color="#55b1a5" stop-opacity="0"/></linearGradient></defs>'+[.2,.5,.8].map(t=>'<line class="chart-grid" x1="'+p+'" x2="'+(W-8)+'" y1="'+(12+(H-32)*t)+'" y2="'+(12+(H-32)*t)+'"/>').join("")+'<polygon class="chart-area" points="'+p+','+(H-20)+' '+pts+' '+(W-8)+','+(H-20)+'"/><polyline class="chart-line" points="'+pts+'"/><line class="anomaly-line" x1="'+x(ai)+'" x2="'+x(ai)+'" y1="'+(y(vals[ai])-17)+'" y2="'+(H-20)+'"/><circle class="anomaly-point" cx="'+x(ai)+'" cy="'+y(vals[ai])+'" r="4"/>'+[0,Math.floor((vals.length-1)/3),Math.floor(2*(vals.length-1)/3),vals.length-1].map((i,j)=>'<text class="chart-tick" x="'+x(i)+'" y="'+(H-2)+'" text-anchor="'+(j===0?"start":j===3?"end":"middle")+'">'+labels[j]+'</text>').join("")+'</svg>'}
function timeline(d){let a=AeroSenseServices.demoPollutionHistory(city);if(range==="7d")a=a.filter((_,i)=>i%3===0);if(range==="30d")a=a.filter((_,i)=>i%5===0);let l=range==="24h"?["00:00","06:00","12:00","18:00"]:range==="7d"?["Mon","Wed","Fri","Sun"]:["Sep 6","Sep 16","Sep 26","Oct 5"],idx=names.indexOf($("#pollutantSelect").value);a=a.map(v=>Math.round(v*[1,.84,.5,.23,.4][idx]+idx*4));$("#timelineChart").innerHTML=lineChart(a,l);$("#anomalyDescription").textContent=$("#pollutantSelect").value+" increased "+Math.round(27+d.rise*.4)+"% between 18:30 and 20:00."}
function forecast(d){let vals=AeroSenseServices.demoPrediction(city),all=[Math.round(d.aqi*.83),Math.round(d.aqi*.93),d.aqi,...vals],W=700,H=132,p=24,max=Math.ceil(Math.max(...all)*1.22/20)*20,x=i=>p+i*(W-p-15)/(all.length-1),y=v=>16+(max-v)*(H-29)/max,pts=all.map((v,i)=>x(i)+","+y(v)).join(" ");$("#forecastChart").innerHTML='<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none"><line x1="'+p+'" x2="'+(W-15)+'" y1="'+y(d.aqi)+'" y2="'+y(d.aqi)+'" stroke="#b9c7c7" stroke-dasharray="4 4"/><polygon points="'+all.slice(2).map((v,i)=>x(i+2)+","+y(v*1.13)).join(" ")+" "+all.slice(2).reverse().map((v,i)=>x(all.length-1-i)+","+y(v*.86)).join(" ")+'" fill="#dcefeb" opacity=".75"/><polyline points="'+pts+'" fill="none" stroke="#3c9e92" stroke-width="2.5" stroke-dasharray="5 4"/>'+all.map((v,i)=>'<text x="'+x(i)+'" y="'+(H-1)+'" text-anchor="middle" fill="#a0adae" font-size="8" font-family="DM Sans">'+(i<2?"−"+(2-i)+"h":"+"+(i-2)+"h")+'</text>').join("")+'</svg>';$("#forecastHours").innerHTML=vals.map((v,i)=>'<div class="forecast-hour"><span>+'+(i+1)+'h</span><b>'+v+' AQI</b><em>'+risk(v)+'</em></div>').join("")}
function advisor(d){let w=d.aqi>180?"Before 7:00 AM":d.aqi>120?"Before 8:00 AM":"Late morning · 10:00 AM";$("#bestWindow").textContent=w;$("#windowAqi").textContent="Predicted AQI: "+d.window+" · "+risk(d.window);$("#profileAdvice").textContent={general:"Choose a shorter, less strenuous outing during this window.",athlete:"Avoid intense outdoor exercise during the predicted pollution peak; consider an indoor session.",child:"Consider outdoor play during the cleaner window and keep activity flexible.",elderly:"Plan a shorter outdoor visit during the lower-pollution window.",sensitive:"Prefer the cleaner window and reduce prolonged exposure if conditions worsen."}[profile]}
function comparison(){$("#compareSelects").innerHTML=compare.map((c,i)=>'<select data-compare="'+i+'" aria-label="Comparison city '+(i+1)+'">'+Object.keys(data).map(n=>'<option '+(n===c?"selected":"")+'>'+n+'</option>').join("")+'</select>').join("");$("#compareChart").innerHTML=compare.map(c=>'<div class="compare-row"><span class="compare-city">'+c+'</span><span class="compare-bar"><i style="width:'+Math.min(100,data[c].aqi/3)+'%"></i></span><span class="compare-val">'+data[c].aqi+'</span></div>').join("");let s=compare.slice().sort((a,b)=>data[a].aqi-data[b].aqi);$("#comparisonSummary").innerHTML='<span class="summary-chip">Cleanest <b>'+s[0]+'</b></span><span class="summary-chip">Highest AQI <b>'+s[s.length-1]+'</b></span><span class="summary-chip">Predicted peak <b>'+compare.slice().sort((a,b)=>Math.max(...data[b].future)-Math.max(...data[a].future))[0]+'</b></span>'}
function history(){$("#historyList").innerHTML=AeroSenseServices.demoHistory(city).map(e=>'<div class="history-event"><span class="history-date">'+e.date+' · '+city.slice(0,3).toUpperCase()+'</span><div><b>'+e.title+'</b><p>'+e.description+'</p><a href="#history">Demo record · no source implied ↗</a></div></div>').join("")}
function recommendations(d){let keys=AeroSenseServices.demoRecommendationKeys(d.aqi),copy={"Limit prolonged outdoor exposure":"Move nonessential outdoor plans to a cleaner time window.","Choose lower-emission travel":"When practical, combine trips or use shared transport.","Check conditions before heading out":"Revisit local air readings later; conditions can change.","Choose a lower-pollution time":"The early morning window is forecast to be cleaner.","Keep outdoor plans flexible":"Consider shortening strenuous activity if air worsens.","Reduce avoidable emissions":"Combine nearby errands or choose shared transport.","Plan around the cleaner window":"Predictions suggest a better time later today.","Prefer lighter activity if needed":"Take breaks if outdoor conditions feel uncomfortable.","Check again before longer outings":"Forecasts are estimates and can shift.","Enjoy outdoor plans thoughtfully":"Current demo conditions are comparatively favorable.","Keep an eye on changing conditions":"Air quality can vary through the day.","Choose shared travel where practical":"Small choices can reduce local emissions."};$("#recIntro").textContent="Guidance adapted to "+risk(d.aqi).toLowerCase()+" conditions."+(profile!=="general"?" Personalized for your selected profile.":"");$("#recommendationsList").innerHTML=keys.map(k=>'<div class="recommendation"><span class="rec-check">✓</span><div><b>'+k+'</b><p>'+copy[k]+'</p></div></div>').join("")}
function toast(m){let t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function modal(title,body){$("#modalTitle").textContent=title;$("#modalBody").textContent=body;$("#modalBackdrop").classList.add("show")}
$("#citySelect").innerHTML=Object.keys(data).map(c=>"<option>"+c+"</option>").join("");$("#citySelect").addEventListener("change",e=>{city=e.target.value;render()});
$$(".map-marker[data-city]").forEach(b=>b.addEventListener("click",()=>{$("#citySelect").value=b.dataset.city;city=b.dataset.city;render()}));
$("#pollutantSelect").addEventListener("change",()=>timeline(data[city]));$("#rangeTabs").addEventListener("click",e=>{if(e.target.dataset.range){range=e.target.dataset.range;$$('#rangeTabs button').forEach(b=>b.classList.toggle("active",b===e.target));timeline(data[city])}});
$("#profileSelect").addEventListener("change",e=>{profile=e.target.value;advisor(data[city]);recommendations(data[city])});
$("#compareSelects").addEventListener("change",e=>{if(e.target.dataset.compare!==undefined){compare[+e.target.dataset.compare]=e.target.value;comparison()}});
$("#addCompare").addEventListener("click",()=>{if(compare.length>=3){toast("Compare up to three locations at a time.");return}compare.push(Object.keys(data).find(c=>!compare.includes(c)));comparison()});
$("#themeToggle").addEventListener("click",()=>document.body.classList.toggle("dark"));$("#menuToggle").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
let mapZoom=1;function setMapZoom(v){mapZoom=Math.max(1,Math.min(1.28,v));let el=$("#mapVisual");el.style.setProperty("--map-zoom",mapZoom);el.classList.toggle("zoomed",mapZoom>1.02)}
$("#mapReset").addEventListener("click",()=>{setMapZoom(1);toast("Map centered on "+city)});$("#zoomIn").addEventListener("click",()=>setMapZoom(mapZoom+.08));$("#zoomOut").addEventListener("click",()=>setMapZoom(mapZoom-.08));
$$(".more-button").forEach(b=>b.addEventListener("click",()=>modal("Demo chart options","Chart values are simulated. Change the range or pollutant using the controls to explore the available demo series.")));
$("#mapLocations").addEventListener("click",()=>modal("Explore city readings","Choose a city from the location selector or click a marker. All five supported locations are deterministic simulated readings."));
$("#historyInfo").addEventListener("click",()=>modal("Demo environmental history","These sample entries illustrate a future product format only. They are not reports of actual incidents, inspections, violations, or regulatory actions. No source is implied."));
$("#profileOpen").addEventListener("click",()=>modal("Guest workspace","AeroSense runs in Demo Mode. No account is required; your profile choice stays in this browser session."));
$("#profileTop").addEventListener("click",()=>modal("Guest workspace","AeroSense runs in Demo Mode. No account is required; your profile choice stays in this browser session."));
$("#modalClose").addEventListener("click",()=>$("#modalBackdrop").classList.remove("show"));$("#modalOkay").addEventListener("click",()=>$("#modalBackdrop").classList.remove("show"));$("#modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")e.target.classList.remove("show")});document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#modalBackdrop").classList.remove("show")});
let titles={overview:"Overview",trends:"Pollution trends",prediction:"Prediction",history:"Environmental history",recommendations:"Recommendations"};
function go(v){let ids={overview:"overviewView",trends:"timelineSection",prediction:"predictionSection",history:"historySection",recommendations:"recommendationsSection"};document.getElementById(ids[v]||ids.overview).scrollIntoView({behavior:"smooth",block:"start"});$("#crumb").textContent=titles[v];$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===v));$("#sidebar").classList.remove("open")}
$$("[data-view]").forEach(e=>e.addEventListener("click",ev=>{ev.preventDefault();go(e.dataset.view)}));
let obs=new IntersectionObserver(es=>{let v=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;let map={overviewView:"overview",timelineSection:"trends",predictionSection:"prediction",historySection:"history",recommendationsSection:"recommendations"},k=map[v.target.id];if(k){$("#crumb").textContent=titles[k];$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===k))}},{rootMargin:"-20% 0px -68% 0px",threshold:[0,.1,.4]});
["overviewView","timelineSection","predictionSection","historySection","recommendationsSection"].forEach(id=>obs.observe(document.getElementById(id)));
function enterDashboard(){$("#landing").hidden=true;$("#landing").style.display="none";$("#appShell").classList.remove("app-hidden");window.scrollTo({top:0,behavior:"instant"});render()}
function returnHome(e){e.preventDefault();$("#appShell").classList.add("app-hidden");$("#landing").hidden=false;$("#landing").style.display="block";window.scrollTo({top:0,behavior:"smooth"})}
$$("[data-enter]").forEach(b=>b.addEventListener("click",enterDashboard));$("#dashboardBrand").addEventListener("click",returnHome);$("#landingBrand").addEventListener("click",e=>{e.preventDefault();window.scrollTo({top:0,behavior:"smooth"})});
if(location.hash==="#overview"||location.hash==="#dashboard")enterDashboard();else render();
