/* Demo fixtures and normalized provider fallbacks live in data.js / services.js. */
const data=window.AeroSenseData.cities;
const names=["PM2.5","PM10","NO2","SO2","O3"], units=["µg/m³","µg/m³","ppb","ppb","ppb"], colors=["#43a399","#e0b84c","#e58c4b","#9b7ab4","#5f9dc0"];
let city="Chennai",range="24h",profile="general",compare=["Chennai","Bengaluru","Hyderabad"],activePayload=null,activeData=data[city],dataMode="auto",requestSerial=0,historyRequestSerial=0,forecastRequestSerial=0,historyRefresh=false,latestAnomaly=null,advisorPoints=[],advisorStatus="unavailable",activeML=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function renderWhy(d,weather){const explainHistory=(activePayload?.status||"demo")==="demo"?d.series:(activePayload?.hourly||[]).filter(p=>p.time&&Number.isFinite(p.pm25)&&AeroSensePrediction.timestampMs(p.time,"+05:30")<=Date.now()).slice(-8).map(p=>p.pm25),providerValues=advisorPoints.filter(p=>p.source==="Open-Meteo").map(p=>p.value),insights=AeroSenseIntelligence.explain({pm25:d.pm,pm10:d.pm10,history:explainHistory,weather,anomaly:latestAnomaly,ml:activeML,providerTrend:providerValues.length?AeroSenseIntelligence.classify(providerValues):null});$("#whySummary").textContent=insights.length?insights.slice(0,2).map(i=>i.explanation).join(" "):"Not enough measured environmental context to describe possible contributors.";$("#factors").innerHTML=insights.length?insights.map(i=>'<div class="factor intelligence-factor"><span class="factor-name">'+i.label+'</span><span class="factor-bar"><i style="width:'+(i.indicator===null?0:i.indicator)+'%"></i></span><span class="factor-level">'+i.status+'</span><small>'+i.explanation+'</small></div>').join(""):'<p class="intelligence-empty">Weather variables or recent observations are unavailable for this location.</p>'}
function risk(n){return n<=50?"Good":n<=100?"Moderate":n<=150?"Sensitive groups":n<=200?"Unhealthy":n<=300?"Very unhealthy":"Hazardous"}
function color(n){return n<=50?"#4e9c73":n<=100?"#a1812d":n<=150?"#aa753c":n<=200?"#b56e36":n<=300?"#ac5c52":"#905889"}
function spark(a,c){let mn=Math.min(...a),mx=Math.max(...a),p=a.map((v,i)=>(i*56/(a.length-1))+","+ (20-(v-mn)/(mx-mn||1)*16)).join(" ");return '<svg class="spark" viewBox="0 0 56 22"><polyline fill="none" stroke="'+c+'" stroke-width="1.5" points="'+p+'"/></svg>'}
function render(){
 const d={...data[city],...activeData},status=activePayload?.status||"demo",sv=d.aqi===null?"#829297":color(d.aqi),weather=d.weather||AeroSenseServices.demoWeather(city),now=Date.now();
 const keys=["pm25","pm10","no2","so2","o3"],values=[d.pm,d.pm10,d.no2,d.so2,d.o3];
 const livePoints=status==="demo"?[]:(activePayload?.hourly||[]).filter(p=>p.time&&Date.parse(p.time+"+05:30")<=now&&Date.parse(p.time+"+05:30")>=now-86400000);
 $("#weatherMini").textContent=(weather.source==="DEMO DATA"&&status!=="demo"?"Demo weather · ":"")+(weather.tempC===null?"—":weather.tempC+"°")+" · "+(weather.summary||"Weather unavailable");
 $("#aqiNumber").textContent=d.aqi??"—";$("#aqiNumber").style.color=sv;$("#riskTag").textContent=d.aqi===null?"UNAVAILABLE":risk(d.aqi).toUpperCase();$("#riskTag").style.color=sv;
 $("#aqiCopy").textContent=d.aqi===null?"No usable AQI was returned for this location.":d.aqi>150?"Air quality is elevated. Sensitive groups may notice effects.":d.aqi>100?"Some people may be affected, especially during prolonged outdoor activity.":"Air conditions are relatively favorable for most everyday activities.";
 $("#changeValue").textContent=(d.delta>0?"↗ ":"↘ ")+Math.abs(d.delta||0)+"%";$("#changeValue").style.color=d.delta>0?"#d68043":"#4c9d7d";$("#primaryPollutant").innerHTML="PM2.5 <span>· "+(d.pm===null?"Unavailable":d.pm+" µg/m³")+"</span>";$("#outlookText").textContent="Forecast loading…";
 $("#airDataSource").textContent=activePayload?.air?.source||"DEMO DATA";$("#airDataNote").textContent=status==="demo"?"ⓘ Deterministic demo fixtures · no live feed available.":"ⓘ CAMS model forecast, not a ground-monitor reading.";
 $("#aqiMeter").style.left=d.aqi===null?"0%":Math.min(94,d.aqi/5)+"%";$("#aqiMeter").style.background=sv;
 $("#pollutantDataStatus").textContent=status==="demo"?"●  DEMO DATA":status==="stale"?"●  STALE MODEL":"●  OPEN-METEO MODEL";$("#footerDataMode").textContent=status==="demo"?"DEMO BUILD · SIMULATED ENVIRONMENTAL DATA":status==="stale"?"STALE MODEL DATA · DEMO FORECASTS / HISTORY":"OPEN-METEO MODEL DATA · DEMO FORECASTS / HISTORY";
 const statusEl=$("#dataStatus");statusEl.className="demo-chip status-"+status;statusEl.innerHTML="<span></span>"+(status==="live"?"LIVE MODEL DATA":status==="partial"?"PARTIAL MODEL DATA":status==="stale"?"STALE MODEL DATA":"DEMO DATA");$("#modeToggle").textContent=dataMode==="demo"?"Try live data":"Use demo data";const stamp=activePayload?.timestamp;$("#updatedLabel").textContent=stamp?(status==="stale"?"Last model time · ":"Model time · ")+stamp:(status==="demo"?"Fixed demo fixtures":"Waiting for feed");
 const cardUnits=names.map((_,i)=>status==="demo"?units[i]:"µg/m³");
 $("#pollutants").innerHTML=values.map((v,i)=>{const series=status==="demo"?d.series.slice(-8).map(x=>x*(.45+i*.1)):livePoints.map(p=>p[keys[i]]).filter(Number.isFinite).slice(-8);const pair=series.slice(-2);const ch=status==="demo"?Math.round((d.delta||0)*[.8,.55,.4,.22,.3][i]):pair.length===2&&pair[0]!==0?Math.round((pair[1]-pair[0])/pair[0]*100):null;const state=v===null?"Unavailable":v>100?"High":v>45?"Elevated":v>25?"Moderate":"Low";const trend=ch===null?'<span>—</span><span>Change unavailable</span>':'<span class="'+(ch>0?"trend-up":"")+'">'+(ch>0?"↗ ":"↘ ")+Math.abs(ch)+'%</span><span>'+(status==="demo"?"vs demo period":"vs prior model hour")+'</span>';const sparkline=series.length>1?spark(series,colors[i]):'<small class="trend-unavailable">Trend unavailable</small>';return '<article class="card pollutant-card"><div class="poll-top"><span class="poll-name">'+names[i]+(status!=="demo"&&i>1?" · µg/m³":"")+'</span><span class="poll-status">'+state+'</span></div><div class="poll-value">'+(v===null?"—":v)+' <small>'+cardUnits[i]+'</small></div><div class="poll-change">'+trend+'</div>'+sparkline+'</article>'}).join("");
 renderWhy(d,weather);
 timeline(d);forecast(d);advisor(d);comparison();history();recommendations(d);syncMap()
}
function syncMap(){if(!AeroSenseMap.isReady())return;const items=Object.keys(data).map(name=>AeroSenseServices.getMapSnapshot(name,{demo:dataMode==="demo"}));if(activePayload&&activePayload.city===city&&dataMode!=="demo"){const d=data[city];items[items.findIndex(i=>i.city===city)]={city,latitude:d.latitude,longitude:d.longitude,aqi:activePayload.air.aqi,status:activePayload.status==="stale"?"stale":activePayload.status==="demo"?"demo":"live",source:activePayload.source}}AeroSenseMap.update(items,city)}
function lineChart(vals,labels,anomalies=[]){
 const valid=vals.map((v,i)=>Number.isFinite(v)?{i,v}:null).filter(Boolean);
 if(!valid.length)return '<div class="empty-chart">Data unavailable for this period.</div>';
 const max=Math.max(1,...valid.map(p=>p.v)),W=640,H=130,pad=26,x=i=>pad+i*(W-pad-8)/Math.max(1,vals.length-1),y=v=>12+(max-v)*(H-32)/max;
 const segments=[];let segment=[];
 vals.forEach((v,i)=>{if(Number.isFinite(v))segment.push(x(i)+','+y(v));else if(segment.length){segments.push(segment);segment=[]}});
 if(segment.length)segments.push(segment);
 const area=segments.filter(points=>points.length>1).map(points=>'<polygon class="chart-area" points="'+points[0].split(',')[0]+','+(H-20)+' '+points.join(' ')+' '+points[points.length-1].split(',')[0]+','+(H-20)+'"/>').join('');
 const lines=segments.map(points=>points.length>1?'<polyline class="chart-line" points="'+points.join(' ')+'"/>':'<circle class="chart-live-point" cx="'+points[0].split(',')[0]+'" cy="'+points[0].split(',')[1]+'" r="2.5"/>').join('');
 const anomalyMarks=anomalies.filter(item=>Number.isInteger(item.pointIndex)&&Number.isFinite(vals[item.pointIndex])).map(item=>'<line class="anomaly-line" x1="'+x(item.pointIndex)+'" x2="'+x(item.pointIndex)+'" y1="'+(y(vals[item.pointIndex])-17)+'" y2="'+(H-20)+'"/><circle class="anomaly-point" cx="'+x(item.pointIndex)+'" cy="'+y(vals[item.pointIndex])+'" r="4"><title>'+item.time+': '+vals[item.pointIndex]+' · '+item.direction+' anomaly</title></circle>').join('');
 const ticks=[0,Math.floor((vals.length-1)/3),Math.floor(2*(vals.length-1)/3),vals.length-1];
 return '<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none"><defs><linearGradient id="areaFade" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#55b1a5" stop-opacity=".19"/><stop offset="1" stop-color="#55b1a5" stop-opacity="0"/></linearGradient></defs>'+[.2,.5,.8].map(t=>'<line class="chart-grid" x1="'+pad+'" x2="'+(W-8)+'" y1="'+(12+(H-32)*t)+'" y2="'+(12+(H-32)*t)+'"/>').join('')+area+lines+anomalyMarks+ticks.map((i,j)=>'<text class="chart-tick" x="'+x(i)+'" y="'+(H-2)+'" text-anchor="'+(j===0?'start':j===3?'end':'middle')+'">'+(labels[j]||'')+'</text>').join('')+'</svg>'
}
function timeline(d){
 const ticket=++historyRequestSerial,selectedCity=city,selectedRange=range,pollutant=$("#pollutantSelect").value;
 const pollutantKeys={"PM2.5":"pm25",PM10:"pm10",NO2:"no2",SO2:"so2",O3:"o3"},key=pollutantKeys[pollutant],idx=names.indexOf(pollutant);
 if(dataMode!=="demo"&&(!activePayload||activePayload.city!==selectedCity)){
  $("#timelineSource").textContent="Waiting for selected location data";
  $("#timelineChart").innerHTML='<div class="empty-chart">Loading historical data…</div>';
  $("#anomalyCallout").hidden=true;$("#anomalyKey").hidden=true;return;
 }
 const force=historyRefresh;historyRefresh=false;
 $("#timelineSource").textContent="Loading historical data…";
 $("#timelineChart").innerHTML='<div class="empty-chart">Loading historical data…</div>';
 $("#anomalyCallout").hidden=true;$("#anomalyKey").hidden=true;
 AeroSenseServices.loadHistory(selectedCity,selectedRange,{mode:dataMode,force}).then(payload=>{
  if(ticket!==historyRequestSerial||city!==selectedCity||range!==selectedRange||$("#pollutantSelect").value!==pollutant)return;
  const values=payload.points.map(point=>point[key]),available=values.some(Number.isFinite);
  const parseTime=time=>time.length===10?Date.parse(time+"T00:00:00+05:30"):/Z|[+-]\d\d:\d\d$/.test(time)?Date.parse(time):Date.parse(time+"+05:30");
  const fmt=date=>Number.isFinite(date)?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",timeZone:"Asia/Kolkata"}).format(date):"";
  const pointDate=time=>{if(payload.status==="demo"&&selectedRange==="24h"&&!/Z|[+-]\d\d:\d\d$/.test(time))return Date.parse(time+"Z");return parseTime(time)};
  const first=payload.points[0]?.time,last=payload.points[payload.points.length-1]?.time;
  const interval=first&&last?fmt(pointDate(first))+"–"+fmt(pointDate(last)):"";
  const unit=payload.status==="demo"?units[idx]:"µg/m³";
  const rangeTitle=selectedRange==="24h"?"last 24 hours":selectedRange==="7d"?"previous 7 days":"previous 30 days";
  const statusText=payload.status==="demo"?"DEMO DATA · Deterministic historical demonstration dataset":payload.status==="stale"?"STALE MODEL DATA · Cached Open-Meteo historical model data":"HISTORICAL MODEL DATA · Open-Meteo CAMS archived forecast";
  $("#timelineSource").textContent=statusText+" · "+rangeTitle+" · "+payload.aggregation+" · "+pollutant+" ("+unit+")"+(interval?" · "+interval:"");
  if(!available){$("#timelineSource").textContent+=" · Data unavailable";$("#timelineChart").innerHTML='<div class="empty-chart">Data unavailable for '+pollutant+' in this period.</div>';return}
  const indices=[0,Math.floor((payload.points.length-1)/3),Math.floor(2*(payload.points.length-1)/3),payload.points.length-1];
  const labels=indices.map(i=>{const time=payload.points[i]?.time;if(!time)return"";const date=pointDate(time);return selectedRange==="24h"?new Intl.DateTimeFormat("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Kolkata"}).format(date):fmt(date)});
  const anomaly=AeroSenseAnomaly.analyze(payload.points,key,selectedRange,{dataStatus:payload.status}),latest=anomaly.latest;latestAnomaly=latest;renderWhy({...data[city],...activeData},activePayload?.weather||AeroSenseServices.demoWeather(city));
  $("#timelineChart").innerHTML=lineChart(values,labels,anomaly.anomalies);
  const hasAnomalies=anomaly.anomalies.length>0;
  $("#anomalyKey").hidden=!hasAnomalies;
  $("#anomalyCallout").hidden=false;
  const stateLabel=payload.status==="demo"?"DEMO ANOMALY":payload.status==="stale"?"STALE-DATA ANOMALY":"HISTORICAL MODEL DATA ANOMALY";
  const unitText=unit;
  if(latest.status==="insufficient"){
   $("#anomalyHeadline").textContent="Insufficient history to assess anomalies";
   $("#anomalyDescription").textContent="Need at least "+anomaly.config.minBaseline+" valid, uniquely timestamped prior readings.";
   $("#anomalySeverity").textContent=payload.status==="demo"?"DEMO DATA":payload.status==="stale"?"STALE DATA":"HISTORICAL DATA";
  }else if(latest.status==="anomalous"){
   const direction=latest.direction==="low"?"LOW":"HIGH";
   $("#anomalyHeadline").textContent="Unusual "+pollutant+" level detected · "+direction+" ANOMALY";
   const date=fmt(pointDate(latest.time)),timeLabel=selectedRange==="24h"?new Intl.DateTimeFormat("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Kolkata"}).format(pointDate(latest.time)):date;
   const score=latest.score===null?"constant baseline deviation":latest.method==="rolling-median-mad"?"robust score "+latest.score.toFixed(2):"standard deviation score "+latest.score.toFixed(2);
   $("#anomalyDescription").textContent=latest.current+" "+unitText+" vs recent baseline "+latest.baseline+" "+unitText+" · "+timeLabel+" · "+score+" · Statistical anomaly — not a causal diagnosis.";
   $("#anomalySeverity").textContent=stateLabel;
  }else{
   $("#anomalyHeadline").textContent="No unusual pollution spike detected";
   $("#anomalyDescription").textContent="Latest "+pollutant+" value is within its recent statistical baseline. No causal conclusion is implied.";
   $("#anomalySeverity").textContent=payload.status==="demo"?"DEMO DATA":payload.status==="stale"?"STALE DATA":"HISTORICAL DATA";
  }
 }).catch(error=>{
  if(ticket!==historyRequestSerial)return;
  $("#timelineSource").textContent="HISTORICAL DATA UNAVAILABLE · "+pollutant;
  $("#timelineChart").innerHTML='<div class="empty-chart">Historical data unavailable.</div>';
  $("#anomalyCallout").style.display="none";$("#anomalyKey").style.display="none";
  console.error("Historical chart failed",error);
 });
}
async function showMLComparison(selectedCity,providerPoint,ticket,providerStatus){
 const panel=$("#mlComparison");panel.hidden=false;panel.innerHTML="";
 const heading=document.createElement("b");heading.textContent="MODEL COMPARISON · PM2.5 · 1 HOUR AHEAD";panel.appendChild(heading);
 const note=document.createElement("p");note.textContent="AeroSense ML is a locally trained Random Forest using recent PM2.5 observations. Open-Meteo values are provider atmospheric-model output. Neither is universally more accurate.";panel.appendChild(note);
 if(dataMode==="demo"||providerStatus==="demo"){
  const status=document.createElement("span");status.className="ml-unavailable";status.textContent="DEMO DATA · trained model not queried; provider demo forecast remains active.";panel.appendChild(status);return null;
 }
 if(!activePayload||!["live","partial"].includes(activePayload.status)){
  const status=document.createElement("span");status.className="ml-unavailable";status.textContent="AEROSENSE ML UNAVAILABLE · current observations are not live; provider forecast is shown.";panel.appendChild(status);return null;
 }
 try{
  const result=await AeroSenseServices.loadAeroSenseML(selectedCity,activePayload);
  if(ticket!==forecastRequestSerial||selectedCity!==city)return;
  const grid=document.createElement("div");grid.className="ml-comparison-values";
  [["AEROSENSE ML",result.value,"Random Forest v"+result.model_version+" · 1-hour ahead"],["PROVIDER FORECAST",providerPoint?.value??null,"Open-Meteo atmospheric model"]].forEach(([label,value,source])=>{
   const item=document.createElement("div"),name=document.createElement("span"),reading=document.createElement("b"),desc=document.createElement("small");item.className="ml-value";name.textContent=label;reading.textContent=Number.isFinite(value)?Number(value).toFixed(1)+" µg/m³":"Unavailable";desc.textContent=source;item.append(name,reading,desc);grid.appendChild(item)
  });panel.appendChild(grid);
  const metric=document.createElement("small"),ml=result.evaluation.test_ml,persist=result.evaluation.test_persistence;
  metric.textContent="Held-out Nov–Dec 2024 test · ML MAE "+ml.mae.toFixed(2)+" / RMSE "+ml.rmse.toFixed(2)+" / R² "+ml.r2.toFixed(3)+" · persistence MAE "+persist.mae.toFixed(2)+" µg/m³.";panel.appendChild(metric);
  const prov=document.createElement("small");prov.className="ml-provenance";prov.textContent="Training: "+result.dataset+" · CC BY 4.0 · CPCB 2024 · generated "+new Date(result.generated_at).toLocaleString()+". One-hour estimate; no confidence percentage.";panel.appendChild(prov);
  activeML=result;return result;
 }catch(error){if(ticket!==forecastRequestSerial||selectedCity!==city)return;console.warn("AeroSense ML request failed; continuing with provider forecast.",{city:selectedCity,message:error?.message||"Unknown request error"});const status=document.createElement("span");status.className="ml-unavailable";status.textContent="AEROSENSE ML UNAVAILABLE · "+(error?.message||"Request failed")+" · provider forecast remains displayed.";panel.appendChild(status)}
}
function updateAdvisor(points,status,ml){const merged=[];if(ml?.value!=null&&ml?.valid_time)merged.push({timestamp:ml.valid_time,value:Number(ml.value),source:"AeroSense ML"});const mt=ml?.valid_time?Date.parse(ml.valid_time):NaN;points.forEach(p=>{if(!Number.isFinite(mt)||Date.parse(p.timestamp)>mt+1800000)merged.push({...p,source:"Open-Meteo"})});advisorPoints=merged;advisorStatus=status;const result=AeroSenseIntelligence.advise({points:merged,profile,status}),fmt=p=>p?.timestamp?new Intl.DateTimeFormat("en-IN",{hour:"numeric",hour12:true,timeZone:"Asia/Kolkata"}).format(Date.parse(p.timestamp)):"—";$("#advisorProvenance").textContent=result.provenance+" · "+result.profile;if(!result.best){$("#bestWindow").textContent="No clear window";$("#windowAqi").textContent=result.message;$("#worstWindow").textContent="—";$("#worstAqi").textContent="Need additional future PM2.5 values."}else{$("#bestWindow").textContent=fmt(result.best);$("#windowAqi").textContent="Predicted PM2.5 "+Number(result.best.value).toFixed(1)+" µg/m³ · "+result.best.source;$("#worstWindow").textContent=fmt(result.worst);$("#worstAqi").textContent="Predicted PM2.5 "+Number(result.worst.value).toFixed(1)+" µg/m³ · "+result.worst.source}$("#profileAdvice").textContent=result.message;renderWhy({...data[city],...activeData},activePayload?.weather||AeroSenseServices.demoWeather(city))}
function refreshAdvisorPM25(ticket,selectedCity){const options={mode:dataMode,dataStatus:activePayload?.status||"demo",payload:activePayload,currentValue:({...data[selectedCity],...activeData}).pm};const provider=AeroSenseServices.loadPrediction(selectedCity,"PM2.5",options);const mlTask=dataMode==="demo"||!activePayload||!["live","partial"].includes(activePayload.status)?Promise.resolve(null):AeroSenseServices.loadAeroSenseML(selectedCity,activePayload).catch(error=>{console.warn("AeroSense ML unavailable to activity advisor; provider forecast remains active.",{city:selectedCity,message:error?.message||"Unknown request error"});return null});Promise.all([provider,mlTask]).then(([prediction,ml])=>{if(ticket!==forecastRequestSerial||city!==selectedCity)return;updateAdvisor(prediction.values.map(p=>({timestamp:p.timestamp,value:p.value,weather:p.weather})),prediction.status,ml)}).catch(error=>{if(ticket!==forecastRequestSerial||city!==selectedCity)return;console.warn("PM2.5 activity forecast unavailable.",{city:selectedCity,message:error?.message||"Unknown request error"});updateAdvisor([],"unavailable",null)})}
function forecast(d){
 const pollutant=$("#pollutantSelect").value,key={"PM2.5":"pm25",PM10:"pm10",NO2:"no2",SO2:"so2",O3:"o3"}[pollutant],current=d[key==="pm25"?"pm":key],ticket=++forecastRequestSerial,selectedCity=city;
 $("#mlComparison").hidden=true;activeML=null;advisorPoints=[];$("#intelligenceOutlook").innerHTML="";
 const unit=pollutant==="PM2.5"||pollutant==="PM10"?"µg/m³":"ppb",stamp=time=>new Intl.DateTimeFormat("en-IN",{hour:"numeric",hour12:true,timeZone:"Asia/Kolkata"}).format(AeroSensePrediction.timestampMs(time,"+05:30")),summary=trend=>({rising:pollutant+" is expected to rise over the next few hours.",falling:pollutant+" is expected to ease over the next few hours.",stable:pollutant+" is expected to remain relatively stable.",mixed:pollutant+" shows a mixed short-term trend.",unavailable:"Not enough forecast values to determine a trend."}[trend]||"Forecast unavailable for this pollutant.");
 $("#forecastInsight").textContent="Loading "+pollutant+" forecast…";$("#forecastSource").textContent="—";$("#forecastStatus").textContent="Loading";$("#forecastChart").innerHTML='<div class="empty-chart">Loading forecast…</div>';$("#forecastHours").innerHTML="";
 AeroSenseServices.loadPrediction(selectedCity,pollutant,{mode:dataMode,dataStatus:activePayload?.status||"demo",payload:activePayload,currentValue:current}).then(prediction=>{
  if(ticket!==forecastRequestSerial||selectedCity!==city||pollutant!==$("#pollutantSelect").value)return;
  const state=prediction.status;$("#forecastStatus").textContent=state==="live"?"LIVE FORECAST":state==="stale"?"STALE FORECAST":state==="demo"?"DEMO FORECAST":"FORECAST UNAVAILABLE";$("#forecastStatus").className="forecast-status forecast-status-"+state;
  $("#forecastSource").textContent=state==="demo"?"Deterministic city fixture":state==="live"||state==="stale"?"Open-Meteo atmospheric model":"—";$("#forecastInsight").textContent=state==="unavailable"?"Forecast unavailable for this pollutant.":summary(prediction.trend);$("#outlookText").textContent=state==="unavailable"?"Forecast unavailable":prediction.trend.charAt(0).toUpperCase()+prediction.trend.slice(1);
  if(state==="unavailable"||!prediction.values.length){$("#forecastChart").innerHTML='<div class="empty-chart">Forecast unavailable for this pollutant.</div>';$("#forecastHours").innerHTML="";$("#forecastTransitionLabel").textContent="Forecast begins here";$("#forecastFootnote").textContent=prediction.error||"No valid future values are available.";if(pollutant==="PM2.5")updateAdvisor([],"unavailable",null);else refreshAdvisorPM25(ticket,selectedCity);return}
  const now=Date.now(),observed=state==="demo"?[]:(activePayload?.hourly||[]).filter(point=>point.time&&Number.isFinite(point[key])&&AeroSensePrediction.timestampMs(point.time,"+05:30")<=now).slice(-5).map(point=>({time:point.time,value:point[key]}));
  if(Number.isFinite(current)){const last=observed[observed.length-1];if(!last||Math.abs(AeroSensePrediction.timestampMs(last.time,"+05:30")-now)>1800000)observed.push({time:new Date(now).toISOString(),value:current})}
  const future=prediction.values,items=[...observed,...future.map(point=>({time:point.timestamp,value:point.value,future:true}))],W=700,H=132,left=32,right=690,top=14,bottom=106,all=items.map(item=>item.value),lo=Math.min(...all),hi=Math.max(...all),pad=Math.max((hi-lo)*.18,1),min=lo-pad,max=hi+pad,x=i=>left+i*(right-left)/Math.max(items.length-1,1),y=value=>top+(max-value)*(bottom-top)/(max-min),futureStart=observed.length?observed.length-1:0,makePoints=from=>items.slice(from).map((item,index)=>x(from+index)+","+y(item.value)).join(" "),futurePoints=makePoints(futureStart),observedPoints=makePoints(0).split(" ").slice(0,observed.length).join(" "),grid=[.25,.5,.75].map(t=>'<line class="forecast-grid" x1="'+left+'" x2="'+right+'" y1="'+(top+(bottom-top)*t)+'" y2="'+(top+(bottom-top)*t)+'"/>').join(""),transitionX=x(futureStart),markers=items.map((item,index)=>'<circle class="forecast-point '+(item.future?"forecast-future-point":"forecast-observed-point")+'" cx="'+x(index)+'" cy="'+y(item.value)+'" r="3"><title>'+stamp(item.time)+': '+item.value+' '+unit+(item.future?" · forecast":" · observed")+'</title></circle>').join(""),ticks=[0,Math.floor((items.length-1)/2),items.length-1].filter((v,i,a)=>a.indexOf(v)===i);
  $("#forecastTransitionLabel").textContent="Forecast begins here"+(observed.length?" · "+stamp(future[0].timestamp):" · no current observation");
  $("#forecastChart").innerHTML='<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none" aria-label="'+pollutant+' current and future forecast"><g>'+grid+'</g>'+((observed.length>1&&observedPoints)?'<polyline class="forecast-observed-line" points="'+observedPoints+'"/>':'')+'<line class="forecast-transition" x1="'+transitionX+'" x2="'+transitionX+'" y1="'+top+'" y2="'+bottom+'"/><polyline class="forecast-provider-line" points="'+futurePoints+'"/>'+markers+ticks.map(index=>'<text class="forecast-axis" x="'+x(index)+'" y="'+(H-3)+'" text-anchor="'+(index===0?"start":index===items.length-1?"end":"middle")+'">'+stamp(items[index].time)+'</text>').join("")+'</svg>';
  $("#forecastHours").innerHTML=future.map(point=>'<div class="forecast-hour"><span>'+stamp(point.timestamp)+'</span><b>'+Number(point.value.toFixed(1))+' '+unit+'</b><em>'+pollutant+' · forecast</em></div>').join("");
  const weatherCount=future.filter(point=>point.weather&&Object.values(point.weather).some(Number.isFinite)).length,horizon=future.length===6?"next 6 hours":"next "+future.length+" hours";$("#forecastKicker").textContent="FORECAST · "+horizon.toUpperCase();$("#forecastFootnote").textContent=(future.length<6?"Forecast available for "+horizon+". ":"")+(state==="demo"?"DEMO FORECAST · deterministic fixture; no confidence estimate is provided.":state==="stale"?"Last valid provider forecast · labelled stale. ":"Open-Meteo future values are atmospheric model output. ")+(weatherCount?"Hourly weather context is available for "+weatherCount+" forecast hours; no causal relationship is implied.":state==="demo"?"No future weather context is included in the demo fixture.":"No future weather context was returned.");
  const finish=ml=>{if(ticket!==forecastRequestSerial||selectedCity!==city)return;const sequence=[];if(Number.isFinite(current))sequence.push({label:"CURRENT",value:current,source:activePayload?.status==="demo"?"DEMO DATA":"OBSERVED"});if(ml?.value!=null)sequence.push({label:"+1 HOUR",value:Number(ml.value),source:"AEROSENSE ML · RANDOM FOREST"});future.forEach((p,i)=>{if(ml?.value!=null&&i===0)return;sequence.push({label:"+"+(i+1)+" HOUR",value:p.value,source:state==="demo"?"DEMO FORECAST":"OPEN-METEO PROVIDER"})});const trend=AeroSenseIntelligence.classify(sequence.map(p=>p.value)),copy={rising:"Values are trending upward across the displayed outlook.",falling:"Values are trending downward across the displayed outlook.",stable:"Values are relatively stable across the displayed outlook.",mixed:"Values move in both directions across the displayed outlook."};$("#intelligenceOutlook").innerHTML=sequence.map(p=>'<div class="outlook-step"><small>'+p.label+'</small><b>'+Number(p.value).toFixed(1)+' '+unit+'</b><span>'+p.source+'</span></div>').join('<span class="outlook-arrow" aria-hidden="true">↓</span>')+(copy[trend]?'<p class="outlook-trend"><b>DERIVED INSIGHT · '+trend.toUpperCase()+'</b> '+copy[trend]+'</p>':'');if(pollutant==="PM2.5")updateAdvisor(future.map(p=>({timestamp:p.timestamp,value:p.value,weather:p.weather,aqi:p.aqi,pm10:p.pm10})),state,ml);else refreshAdvisorPM25(ticket,selectedCity)};
  if(pollutant==="PM2.5")showMLComparison(selectedCity,future[0],ticket,state).then(finish);else{$("#mlComparison").hidden=true;finish(null)}
 }).catch(error=>{if(ticket!==forecastRequestSerial)return;$("#forecastInsight").textContent="Forecast unavailable for this pollutant.";$("#forecastSource").textContent="—";$("#forecastStatus").textContent="FORECAST UNAVAILABLE";$("#forecastChart").innerHTML='<div class="empty-chart">Forecast unavailable for this pollutant.</div>';$("#forecastHours").innerHTML="";$("#forecastFootnote").textContent="The forecast could not be loaded. Other dashboard data remains available.";console.error("Forecast failed",error)})
}
function advisor(d){updateAdvisor([],"unavailable",null)}
function comparison(){$("#compareSelects").innerHTML=compare.map((c,i)=>'<select data-compare="'+i+'" aria-label="Comparison city '+(i+1)+'">'+Object.keys(data).map(n=>'<option '+(n===c?"selected":"")+'>'+n+'</option>').join("")+'</select>').join("");$("#compareChart").innerHTML=compare.map(c=>'<div class="compare-row"><span class="compare-city">'+c+'</span><span class="compare-bar"><i style="width:'+Math.min(100,data[c].aqi/3)+'%"></i></span><span class="compare-val">'+data[c].aqi+'</span></div>').join("");let s=compare.slice().sort((a,b)=>data[a].aqi-data[b].aqi),spread=Math.max(...compare.map(c=>data[c].aqi))-Math.min(...compare.map(c=>data[c].aqi));$("#comparisonSummary").innerHTML='<span class="summary-chip">Cleanest <b>'+s[0]+'</b></span><span class="summary-chip">Highest AQI <b>'+s[s.length-1]+'</b></span><span class="summary-chip">AQI spread <b>'+spread+' points</b></span>'}
function history(){$("#historyList").innerHTML=AeroSenseServices.demoHistory(city).map(e=>'<div class="history-event"><span class="history-date">'+e.date+' · '+city.slice(0,3).toUpperCase()+'</span><div><b>'+e.title+'</b><p>'+e.description+'</p><a href="#history">Demo record · no source implied ↗</a></div></div>').join("")}
function recommendations(d){let keys=AeroSenseServices.demoRecommendationKeys(d.aqi),copy={"Limit prolonged outdoor exposure":"Move nonessential outdoor plans to a cleaner time window.","Choose lower-emission travel":"When practical, combine trips or use shared transport.","Check conditions before heading out":"Revisit local air readings later; conditions can change.","Choose a lower-pollution time":"The early morning window is forecast to be cleaner.","Keep outdoor plans flexible":"Consider shortening strenuous activity if air worsens.","Reduce avoidable emissions":"Combine nearby errands or choose shared transport.","Plan around the cleaner window":"Predictions suggest a better time later today.","Prefer lighter activity if needed":"Take breaks if outdoor conditions feel uncomfortable.","Check again before longer outings":"Forecasts are estimates and can shift.","Enjoy outdoor plans thoughtfully":"Current demo conditions are comparatively favorable.","Keep an eye on changing conditions":"Air quality can vary through the day.","Choose shared travel where practical":"Small choices can reduce local emissions."};$("#recIntro").textContent=d.aqi===null?"Current AQI unavailable. Showing general demo guidance.":"Guidance adapted to "+risk(d.aqi).toLowerCase()+" conditions."+(profile!=="general"?" Personalized for your selected profile.":"");$("#recommendationsList").innerHTML=keys.map(k=>'<div class="recommendation"><span class="rec-check">✓</span><div><b>'+k+'</b><p>'+copy[k]+'</p></div></div>').join("")}
function toast(m){let t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function modal(title,body){$("#modalTitle").textContent=title;$("#modalBody").textContent=body;$("#modalBackdrop").classList.add("show")}
async function loadCity(){const ticket=++requestSerial;if(activePayload?.city!==city){activePayload=null;activeData=data[city];render()}$("#dataStatus").className="demo-chip status-loading";$("#dataStatus").innerHTML="<span></span> LOADING DATA";$("#updatedLabel").textContent="Checking Open-Meteo…";$("#refreshData").disabled=true;try{let payload=await AeroSenseServices.load(city,{mode:dataMode});if(ticket!==requestSerial)return;activePayload=payload;activeData=payload.status==="demo"?data[city]:AeroSenseServices.getLiveOptions(payload);render();if(payload.status==="demo"&&payload.error)$("#updatedLabel").textContent="Demo fallback · live feed unavailable"}finally{if(ticket===requestSerial)$("#refreshData").disabled=false}}
$("#citySelect").innerHTML=Object.keys(data).map(c=>"<option>"+c+"</option>").join("");$("#citySelect").addEventListener("change",e=>{city=e.target.value;loadCity()});
$("#pollutantSelect").addEventListener("change",()=>{const d={...data[city],...activeData};timeline(d);forecast(d)});$("#rangeTabs").addEventListener("click",e=>{if(e.target.dataset.range){range=e.target.dataset.range;$$('#rangeTabs button').forEach(b=>b.classList.toggle("active",b===e.target));timeline({...data[city],...activeData})}});
$("#profileSelect").addEventListener("change",e=>{profile=e.target.value;updateAdvisor(advisorPoints,advisorStatus,activeML);recommendations({...data[city],...activeData})});
$("#compareSelects").addEventListener("change",e=>{if(e.target.dataset.compare!==undefined){compare[+e.target.dataset.compare]=e.target.value;comparison()}});
$("#refreshData").addEventListener("click",()=>{dataMode="auto";historyRefresh=true;loadCity()});$("#modeToggle").addEventListener("click",()=>{dataMode=dataMode==="demo"?"auto":"demo";loadCity()});
$("#addCompare").addEventListener("click",()=>{if(compare.length>=3){toast("Compare up to three locations at a time.");return}compare.push(Object.keys(data).find(c=>!compare.includes(c)));comparison()});
$("#themeToggle").addEventListener("click",()=>document.body.classList.toggle("dark"));$("#menuToggle").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
$("#mapReset").addEventListener("click",()=>{AeroSenseMap.fitAll();toast("Showing all five city references")});
$$(".more-button").forEach(b=>b.addEventListener("click",()=>modal("Chart data sources","The 24-hour chart uses hourly Open-Meteo CAMS model output when available. The 7-day and 30-day charts request their own historical ranges and show daily-average pollutant concentrations. These are model outputs, not ground-station measurements. No AQI is calculated from pollutant concentrations. If historical data is unavailable, AeroSense labels cached results STALE or uses clearly labelled deterministic DEMO DATA.")));
$("#mapLocations").addEventListener("click",()=>{AeroSenseMap.fitAll();toast("Showing all five city references")});
$("#historyInfo").addEventListener("click",()=>modal("Demo environmental history","These sample entries illustrate a future product format only. They are not reports of actual incidents, inspections, violations, or regulatory actions. No source is implied."));
$("#profileOpen").addEventListener("click",()=>modal("Guest workspace",activePayload?.status==="demo"?"AeroSense is showing deterministic demo data. No account is required; your profile choice stays in this browser session.":"AeroSense is showing Open-Meteo model data with demo predictions and history. No account is required; your profile choice stays in this browser session."));
$("#profileTop").addEventListener("click",()=>modal("Guest workspace",activePayload?.status==="demo"?"AeroSense is showing deterministic demo data. No account is required; your profile choice stays in this browser session.":"AeroSense is showing Open-Meteo model data with demo predictions and history. No account is required; your profile choice stays in this browser session."));
$("#modalClose").addEventListener("click",()=>$("#modalBackdrop").classList.remove("show"));$("#modalOkay").addEventListener("click",()=>$("#modalBackdrop").classList.remove("show"));$("#modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")e.target.classList.remove("show")});document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#modalBackdrop").classList.remove("show")});
let titles={overview:"Overview",trends:"Pollution trends",prediction:"Prediction",history:"Environmental history",recommendations:"Recommendations"};
function go(v){let ids={overview:"overviewView",trends:"timelineSection",prediction:"predictionSection",history:"historySection",recommendations:"recommendationsSection"};document.getElementById(ids[v]||ids.overview).scrollIntoView({behavior:"smooth",block:"start"});$("#crumb").textContent=titles[v];$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===v));$("#sidebar").classList.remove("open")}
$$("[data-view]").forEach(e=>e.addEventListener("click",ev=>{ev.preventDefault();go(e.dataset.view)}));
let obs=new IntersectionObserver(es=>{let v=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;let map={overviewView:"overview",timelineSection:"trends",predictionSection:"prediction",historySection:"history",recommendationsSection:"recommendations"},k=map[v.target.id];if(k){$("#crumb").textContent=titles[k];$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===k))}},{rootMargin:"-20% 0px -68% 0px",threshold:[0,.1,.4]});
["overviewView","timelineSection","predictionSection","historySection","recommendationsSection"].forEach(id=>obs.observe(document.getElementById(id)));
function enterDashboard(){$("#landing").hidden=true;$("#landing").style.display="none";$("#appShell").classList.remove("app-hidden");window.scrollTo({top:0,behavior:"instant"});if(AeroSenseMap.init(Object.keys(data).map(name=>({city:name,latitude:data[name].latitude,longitude:data[name].longitude})),name=>{city=name;$("#citySelect").value=name;loadCity()})){syncMap();setTimeout(()=>AeroSenseMap.resize(),0)}loadCity()}
function returnHome(e){e.preventDefault();$("#appShell").classList.add("app-hidden");$("#landing").hidden=false;$("#landing").style.display="block";window.scrollTo({top:0,behavior:"smooth"})}
$$("[data-enter]").forEach(b=>b.addEventListener("click",enterDashboard));$("#dashboardBrand").addEventListener("click",returnHome);$("#landingBrand").addEventListener("click",e=>{e.preventDefault();window.scrollTo({top:0,behavior:"smooth"})});
if(["#overview","#dashboard","#trends","#prediction","#history","#recommendations"].includes(location.hash))enterDashboard();else render();
