/* Fixed demo fixtures. These are illustrative, not monitored observations. */
window.AeroSenseData={mode:"demo",cities:{
 Chennai:{aqi:164,pm:78,pm10:126,no2:41,so2:12,o3:33,delta:23,series:[42,39,46,43,50,55,48,57,61,52,65,70,61,73,68,78,74,82,76,91,84,96,89,101],wind:"Low",humidity:"Moderate",temperature:"Moderate",rain:"Low",rise:34,window:108,latitude:13.0827,longitude:80.2707,weather:{tempC:29,windKmh:9,humidityPct:65,precipMm:0,summary:"Warm · light breeze"}},
 Bengaluru:{aqi:92,pm:34,pm10:67,no2:24,so2:7,o3:28,delta:-11,series:[39,41,37,43,40,45,41,39,42,44,48,43,46,40,45,42,44,48,46,43,41,44,39,38],wind:"Moderate",humidity:"Low",temperature:"Moderate",rain:"Moderate",rise:8,window:62,latitude:12.9716,longitude:77.5946,weather:{tempC:26,windKmh:14,humidityPct:54,precipMm:0.4,summary:"Partly cloudy · breeze"}},
 Hyderabad:{aqi:118,pm:51,pm10:89,no2:32,so2:9,o3:36,delta:8,series:[45,43,48,46,50,52,49,55,53,57,54,60,58,64,59,66,62,68,65,72,68,74,71,78],wind:"Low",humidity:"Moderate",temperature:"High",rain:"Low",rise:19,window:79,latitude:17.385,longitude:78.4867,weather:{tempC:30,windKmh:7,humidityPct:49,precipMm:0,summary:"Warm · light breeze"}},
 Delhi:{aqi:212,pm:116,pm10:194,no2:63,so2:19,o3:44,delta:31,series:[65,61,72,69,74,80,75,88,84,91,86,95,102,94,107,112,104,118,113,127,120,134,129,144],wind:"Very low",humidity:"Moderate",temperature:"High",rain:"None",rise:46,window:154,latitude:28.6139,longitude:77.209,weather:{tempC:31,windKmh:4,humidityPct:42,precipMm:0,summary:"Hazy · very light breeze"}},
 Mumbai:{aqi:136,pm:57,pm10:101,no2:37,so2:11,o3:41,delta:14,series:[48,47,52,49,54,51,56,53,59,55,61,58,64,61,67,63,71,68,74,70,79,75,83,80],wind:"Moderate",humidity:"High",temperature:"Moderate",rain:"Low",rise:22,window:84,latitude:19.076,longitude:72.8777,weather:{tempC:30,windKmh:13,humidityPct:77,precipMm:0.1,summary:"Humid · coastal breeze"}}
},recommendationRules:{severe:["Limit prolonged outdoor exposure","Choose lower-emission travel","Check conditions before heading out"],elevated:["Choose a lower-pollution time","Keep outdoor plans flexible","Reduce avoidable emissions"],moderate:["Plan around the cleaner window","Prefer lighter activity if needed","Check again before longer outings"],good:["Enjoy outdoor plans thoughtfully","Keep an eye on changing conditions","Choose shared travel where practical"]}};

window.AeroSenseData.cities.Chennai.predictions={pm25:[82,85,84,80,78,77],pm10:[130,134,132,128,125,123]};
window.AeroSenseData.cities.Bengaluru.predictions={pm25:[33,32,31,30,31,30],pm10:[65,64,63,62,63,62]};
window.AeroSenseData.cities.Hyderabad.predictions={pm25:[52,53,54,56,57,58],pm10:[91,93,95,98,100,102]};
window.AeroSenseData.cities.Delhi.predictions={pm25:[121,124,127,126,122,118],pm10:[198,203,208,206,199,192]};
window.AeroSenseData.cities.Mumbai.predictions={pm25:[57,56,56,55,55,54],pm10:[102,100,99,98,97,96]};

window.AeroSenseData.environmentalRecords=[
 {id:"tnpcb-air-adyar-20260916",region:"Chennai",specific_location:"Adyar",geographic_scope:"Chennai city station · Residential",area_type:"Residential",date:"2026-09-16",title:"Adyar · Residential",category:"Official Air Quality Monitoring",summary:"Official NAMP station measurements for the stated monitoring period. Monitoring results are not compliance findings.",authority:"Tamil Nadu Pollution Control Board",monitoring_period:"16 September 2026 06:00 hrs to 17 September 2026 06:00 hrs",measurements:[{pollutant:"PM10",value:52,unit:"µg/m³"},{pollutant:"PM2.5",value:17,unit:"µg/m³"},{pollutant:"SO2",value:8,unit:"µg/m³"},{pollutant:"NO2",value:15,unit:"µg/m³"},{pollutant:"AQI",value:52,unit:""}],source_document:"ambient_airquality_16_09_26.pdf",source_reference:"Page 1 · Chennai City NAMP table",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-air-nungambakkam-20260916",region:"Chennai",specific_location:"Nungambakkam",geographic_scope:"Chennai city station · Traffic Area",area_type:"Traffic Area",date:"2026-09-16",title:"Nungambakkam · Traffic Area",category:"Official Air Quality Monitoring",summary:"Official NAMP station measurements for the stated monitoring period. Monitoring results are not compliance findings.",authority:"Tamil Nadu Pollution Control Board",monitoring_period:"16 September 2026 06:00 hrs to 17 September 2026 06:00 hrs",measurements:[{pollutant:"PM10",value:64,unit:"µg/m³"},{pollutant:"PM2.5",value:27,unit:"µg/m³"},{pollutant:"SO2",value:13,unit:"µg/m³"},{pollutant:"NO2",value:25,unit:"µg/m³"},{pollutant:"AQI",value:64,unit:""}],source_document:"ambient_airquality_16_09_26.pdf",source_reference:"Page 1 · Chennai City NAMP table",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-atul-fabs-20260902",region:"Karur",specific_location:"Palvarpatti, Mookanankurichi Village, Manavadi Post, Karur Taluk, Karur District · 639 005",geographic_scope:"Karur District",date:"2026-09-02",title:"M/s. Atul Fabs",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/2307/2026-T2, dated 02.09.2026",regulatory_basis:["Water (P&CP) Act, 1974"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 1 · item 1",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-sri-balaji-dyeing-works-20260905",region:"Salem",specific_location:"New T.S. No. 80, Ward-2, Block-35, Erumapalayam Village, Salem Taluk, Salem · 636 015",geographic_scope:"Salem District",date:"2026-09-05",title:"M/s. Sri Balaji Dyeing Works",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/3157/2026-T2, dated 05.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 1 · item 2",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-kalaimani-crusher-20260905",region:"Perambalur",specific_location:"Therani Village, Alathur Taluk, Perambalur District · 621 109",geographic_scope:"Perambalur District",date:"2026-09-05",title:"M/s. Kalaimani Crusher",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/T3/E-file No. 2508/PMB/Direction for Closure and Disconnection of Power Supply/W/A/2026-1, dated 05.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 1 · item 3",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-cdr-infracon-20260905",region:"Virudhunagar",specific_location:"S.F. No. 85/3B2, S. Kallupatti, Kariapatti Taluk, Virudhunagar District",geographic_scope:"Virudhunagar District",date:"2026-09-05",title:"M/s. CDR Infracon Limited · Hot Mix Plant",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T5/TNPCB/F.2775/VDR/W/A/2026, dated 05.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 1 · item 4",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-spac-starch-products-20260908",region:"Erode",specific_location:"Poonachi Village, Anthiyur Taluk, Erode · 638 314",geographic_scope:"Erode District",date:"2026-09-08",title:"M/s. SPAC Starch Products (India) Private Limited",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T8/TNPCB/F.2708/PND/Closure/W/A/2026, dated 08.09.2026",regulatory_basis:["Water (P&CP) Act, 1974"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 2 · item 5",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-visen-industries-20260905",region:"Kancheepuram",specific_location:"SIPCOT Industrial Park Phase-I, Mambakkam, Irunkulam Village, Sriperumbudur Taluk, Kancheepuram District",geographic_scope:"Kancheepuram District",date:"2026-09-05",title:"M/s. Visen Industries Limited",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T4/TNPCB/F.648/W/A/2026, dated 05.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 2 · item 6",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-yashoda-rice-mill-20260908",region:"Tiruvallur",specific_location:"S.F. No. 82, Chinnamapet Village, Tiruttani Taluk, Tiruvallur District",geographic_scope:"Tiruvallur District",date:"2026-09-08",title:"M/s. Yashoda Rice Mill (Previously Monica Vedhika Maavu Mill)",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T8/TNPCB/F.2684/TLR/Closure & Disconnection of Power Supply/W/A/2026-1, dated 08.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 2 · item 7",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-vishwa-modern-rice-mill-20260908",region:"Madurai",specific_location:"No. 600, Annai Sathya Nagar, Rani Mangammal Road, Sakkimangalam, Silaiman Post, Madurai East Taluk, Madurai District",geographic_scope:"Madurai District",date:"2026-09-08",title:"M/s. Vishwa Modern Rice Mill",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T8/TNPCB/F.2707/MDU/Closure & Disconnection of Power Supply/W/A/2026-1, dated 08.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 2 · item 8",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-thirumagal-dyeing-works-20260912",region:"Karur",specific_location:"S.F. No. 1724/1, 1724/2, 1724/3 (Part), 1725, Andankoil Village, Manmangalam Taluk, Karur District",geographic_scope:"Karur District",date:"2026-09-12",title:"M/s. Thirumagal Dyeing Works",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T2/TNPCB/F.2760/KAR/W/A/2026-1, dated 12.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 2 · item 9",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-sandhiveeran-crusher-20260915",region:"Pudukkottai",specific_location:"S.F. No. 32/1, 32/2, 32/3, 32/5, 32/6 and 33/1, 33/2, 33/3, Themavur Village, Kulathur Taluk, Pudukkottai · 622 507",geographic_scope:"Pudukkottai District",date:"2026-09-15",title:"M/s. Sandhiveeran Crusher",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/T3/E-file No. 2689/PDK/Direction for Closure and Disconnection of Power Supply/W/A/2026-1, dated 15.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 2 · item 10",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-sivashankari-auto-tech-20260920",region:"Kancheepuram",specific_location:"S.F. No. 224 (pt), No. 19, Kalaimagal Nagar, Palanthandalam Village, Kundrathur Taluk, Kancheepuram · 602 132",geographic_scope:"Kancheepuram District",date:"2026-09-20",title:"M/s. Sivashankari Auto Tech",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/T3/E-file No. 2519/SPR/Direction for Closure and Disconnection of Power Supply/W/A/2026-1, dated 20.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 3 · item 11",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-atoz-pharmaceuticals-20260924",region:"Tiruvallur",specific_location:"Plot No. 8, S.F. No. 514/2A1B, 2A1B1C, 2A1B1B, 2A1A2A, Balaji Nagar, Thirumullaivoyal Village, Avadi Taluk, Tiruvallur · 600 062",geographic_scope:"Tiruvallur District",date:"2026-09-24",title:"M/s. ATOZ Pharmaceuticals Pvt Ltd · Unit-II",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/T3/E-file No. 68/TLR/Direction for Closure and Disconnection of Power Supply/W/A/2026-1, dated 24.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 3 · item 12",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-sri-selliamman-20260925",region:"Tiruvallur",specific_location:"No. 99, Ariyathamman Koil Street, near Kathirvelan Body Shop, Kolapancherry, Poonamallee; S. No. 108/2 (part), 109 (part), Kolapancherry Village, Poonamallee Taluk, Tiruvallur District",geographic_scope:"Tiruvallur District",date:"2026-09-25",title:"M/s. Sri Selliamman & Co",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T6/TNPCB/F.76/TLR/W/A/Closure/2026, dated 25.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 3 · item 13",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-icon-ready-mix-20260925",region:"Virudhunagar",specific_location:"S.F. No. 101/3, 101/6, 101/7, Madurai-Kanniyakumari Bypass Road, near Ariyanivas Hotel, Pattampudhur Village, Virudhunagar District",geographic_scope:"Virudhunagar District",date:"2026-09-25",title:"M/s. Icon Ready Mix Concrete",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T6/TNPCB/F.3483/VNR/W/A/Closure/2026, dated 25.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 3 · item 14",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-pride-rmx-20260925",region:"Tiruvallur",specific_location:"S. No. 108/2 (part), 109 (part), Kolapancherri Village, Poonamallee Taluk, Tiruvallur District",geographic_scope:"Tiruvallur District",date:"2026-09-25",title:"M/s. Pride RMX Private Limited",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T6/TNPCB/F.75/TLR/W/A/Closure/2026, dated 25.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 3 · item 15",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-ssv-foundation-20260930",region:"Tiruvallur",specific_location:"S. No. 30, Kolapancherri Village, Poonamallee Taluk, Tiruvallur District",geographic_scope:"Tiruvallur District",date:"2026-09-30",title:"M/s. SSV Foundation · RMC Plant",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. T6/TNPCB/F.77/TLR/W/A/Closure/2026, dated 30.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 4 · item 16",source_url:null,verification_status:"Verified official record"},
 {id:"tnpcb-closure-king-aqua-20260930",region:"Ramanathapuram",specific_location:"S.F. No. 529/1B, Sundaranendal Village, Paramakudi Taluk, Ramanathapuram · 623 707",geographic_scope:"Ramanathapuram District",date:"2026-09-30",title:"M/s. King Aqua",category:"Closure / Sealing Direction",summary:"Listed in the TNPCB register of industries issued with a closure direction/sealing.",authority:"Tamil Nadu Pollution Control Board",proceeding_number:"Proc. No. TNPCB/T3/E-file No. 3340/Direction for Closure and Disconnection of Power Supply/Sealing/W/A/2026-1, dated 30.09.2026",regulatory_basis:["Water (P&CP) Act, 1974","Air (P&CP) Act, 1981"],source_document:"ClosureIndustrySep26.pdf",source_reference:"Page 4 · item 17",source_url:null,verification_status:"Verified official record"}
];
