/* Transparent, deterministic interpretations of observed and forecast inputs. */
(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;if(root)root.AeroSenseIntelligence=api})(typeof window!=="undefined"?window:globalThis,function(){
 const valid=Number.isFinite;
 function trend(values){return globalThis.AeroSensePrediction?.classifyTrend(values)||(()=>{const a=values.filter(valid);if(a.length<2)return{trend:"unavailable"};const mid=Math.floor(a.length/2),delta=a.slice(mid).reduce((x,y)=>x+y,0)/(a.length-mid)-a.slice(0,mid).reduce((x,y)=>x+y,0)/mid;return{trend:delta>0.5?"rising":delta<-.5?"falling":"stable",change:delta}})()}
 function explain(input={}){const out=[],add=(label,status,indicator,explanation,category)=>out.push({label,status,indicator,explanation,category});const w=input.weather||{};const pt=(input.history||[]).filter(valid);const t=trend(pt);
  if(valid(w.windKmh))add("Wind / dispersion",w.windKmh<7?"Weak":"Stronger",Math.round(Math.min(w.windKmh/25,1)*100),w.windKmh<7?"Relatively weak winds may be associated with slower pollutant dispersion.":"Higher wind speeds may support pollutant dispersion; this is not a source attribution.","dispersion");
  if(valid(w.humidityPct)&&w.humidityPct>=70)add("Humidity","High",w.humidityPct,"Higher humidity can coincide with changes in particle measurements.","weather");
  if(valid(w.tempC))add("Temperature",w.tempC>=32?"Warm":w.tempC<12?"Cool":"Moderate",Math.round(Math.max(0,Math.min(100,(w.tempC+5)*1.8))),"Temperature is included as context; its relationship with pollution is not inferred here.","weather");
  if(valid(w.precipMm)&&w.precipMm>0)add("Rainfall",w.precipMm>=2?"Ongoing":"Light",Math.round(Math.min(100,w.precipMm*20)),"Precipitation is present and may coincide with changing particle levels.","weather");
  if(pt.length>=2)add("PM2.5 trend",t.trend,t.change===null?0:Math.min(100,Math.round(Math.abs(t.change)*2)),t.trend==="rising"?"Recent PM2.5 observations are trending upward.":t.trend==="falling"?"Recent PM2.5 observations are trending downward.":t.trend==="mixed"?"Recent PM2.5 observations moved in both directions.":"Recent PM2.5 observations are relatively stable.","pollution");
  if(valid(input.pm10))add("PM10 reading",input.pm10>100?"Elevated":"Available",Math.min(100,Math.round(input.pm10)),"Current PM10 is shown as a co-pollutant observation; no source is inferred.","pollution");
  if(input.anomaly?.status==="anomalous")add("Recent statistical anomaly",input.anomaly.direction==="low"?"Unusually low":"Unusually high",Math.min(100,Math.round(input.anomaly.score||0)),"A recent value differs from its statistical baseline; an anomaly is not a causal diagnosis.","anomaly");
  if(input.ml?.value!=null&&valid(input.ml.value))add("AeroSense ML", "1-hour estimate",null,"Random Forest estimates PM2.5 at "+Number(input.ml.value).toFixed(1)+" µg/m³ one hour ahead.","prediction");
  if(input.providerTrend&&input.providerTrend!=="unavailable")add("Provider forecast",input.providerTrend,null,"Open-Meteo provider values indicate a "+input.providerTrend+" near-term trend.","prediction");return out;
 }
 function classify(values){return trend(values).trend}
 const profiles={general:{label:"General public",limit:35,factor:1},walking:{label:"Walking",limit:35,factor:1},running:{label:"Running",limit:25,factor:1.3},cycling:{label:"Cycling",limit:25,factor:1.25},sensitive:{label:"Sensitive groups",limit:15,factor:1.5}};
 function advise(input={}){const profile=profiles[input.profile]||profiles.general;const points=(input.points||[]).filter(p=>valid(p.value)).map(p=>{const particlePenalty=Math.max(0,p.value)*.6+Math.max(0,p.value-profile.limit)*profile.factor,weatherPenalty=valid(p.weather?.windKmh)&&p.weather.windKmh<7?2:0,aqiPenalty=valid(p.aqi)?Math.max(0,p.aqi-50)*.12:0,coPollutantPenalty=valid(p.pm10)?Math.max(0,p.pm10-50)*.04:0;return{...p,score:100-particlePenalty-weatherPenalty-aqiPenalty-coPollutantPenalty}}).sort((a,b)=>(Date.parse(a.timestamp)||0)-(Date.parse(b.timestamp)||0));const provenance=input.status==="demo"?"DEMO FORECAST":input.status==="stale"?"STALE FORECAST":input.status==="live"?"PROVIDER FORECAST":"FORECAST UNAVAILABLE";
  if(points.length<2)return{profile:profile.label,provenance,best:null,worst:null,message:"At least two future PM2.5 values are needed to compare activity windows."};const vals=points.map(p=>p.value),tr=trend(vals),min=Math.min(...vals),max=Math.max(...vals),meaningful=max-min>=1;const best=meaningful?points.reduce((a,b)=>b.score>a.score?b:a):null,worst=meaningful?points.reduce((a,b)=>b.score<a.score?b:a):null;return{profile:profile.label,provenance,best,worst,trend:tr.trend,meaningful,message:meaningful?"Window ranking uses predicted PM2.5, available AQI/co-pollutant/weather context, and this activity profile. General guidance, not medical advice.":"Forecast PM2.5 is nearly flat; no meaningfully better or worse window is identified."};
 }
 function provenance(status,kind="data"){if(kind==="ml"&&status==="unavailable")return"ML UNAVAILABLE";if(kind==="ml"&&status==="demo")return"DEMO ML ESTIMATE";if(kind==="provider")return status==="demo"?"DEMO FORECAST":status==="stale"?"STALE FORECAST":"PROVIDER FORECAST";return status==="live"||status==="partial"?"LIVE MODEL DATA":status==="stale"?"STALE DATA":"DEMO DATA"}
 return{trend,classify,explain,advise,provenance,profiles};
});
